language: ruby
rvm:
- 2.1.2
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
before_script:
- cp config/database.yml.sample config/database.yml
- psql -c 'create database ipsilon_test' -U postgres
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake db:seed RAILS_ENV=test
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: GI19eRobuRJvcdzV9P0iFtGjbDG7xzHEc18ovf55XCjj0Z2OTeROaMtK1Gk8QnjFt9LSuXUV+vULWRMrPpER/rZ90DajOaMwKDbYoecxUU2x8KvbR6GTxOiEEPdim0WVz0szA6S62mZ2MPV1iI3jgdkex+GYbfXIG0OT+8ucQKo=
  app:
    master: ipsilonrb
    dev: ipsilondev
  on:
    repo: jlrogee/ipsilon
    branch: dev master
  run:
  - "rake db:migrate"
  - "rake db:seed"