language: ruby
rvm:
- 2.1.2
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
before_script:
- cp config/database.yml.sample config/database.yml
- psql -c 'create database ipsilon_test' -U postgres
- psql -c 'create database ipsilon_prod' -U postgres
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake db:seed RAILS_ENV=test
- bundle exec rspec spec
