language: ruby
rvm:
  - 2.1.2
 env:
  - DB=postgresql
 script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
 before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database pm_test' -U postgres
 deploy:
  provider: heroku
  api_key: "f5cfe541-52bc-4a5a-a32b-d06b0e8779fe"
  app: ipsilonrb
  run: "rake db:migrate"