language: ruby
rvm:
- 2.1.2
env:
- DB=postgresql
before_install:
- gem update --system 2.2.2
- gem --version
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
- bundle exec rspec spec
before_script:
- cp config/database.yml.sample config/database.yml
- psql -c 'create database ip_test' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: GI19eRobuRJvcdzV9P0iFtGjbDG7xzHEc18ovf55XCjj0Z2OTeROaMtK1Gk8QnjFt9LSuXUV+vULWRMrPpER/rZ90DajOaMwKDbYoecxUU2x8KvbR6GTxOiEEPdim0WVz0szA6S62mZ2MPV1iI3jgdkex+GYbfXIG0OT+8ucQKo=
  app: ipsilonrb
  on:
    repo: jlrogee/ipsilon
  run:
  - "rake db:migrate"
  - "rake db:seed"